// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: speedtest.sql

package db

import (
	"context"
)

const addNodeSpeedTest = `-- name: AddNodeSpeedTest :one
INSERT INTO node_speedtests (node_id, at, ping_ms, jitter_ms, loss_pct, down_bps, up_bps, error)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, node_id, at, ping_ms, jitter_ms, loss_pct, down_bps, up_bps, error
`

type AddNodeSpeedTestParams struct {
	NodeID   int64
	At       int64
	PingMs   float64
	JitterMs float64
	LossPct  float64
	DownBps  int64
	UpBps    int64
	Error    string
}

func (q *Queries) AddNodeSpeedTest(ctx context.Context, arg AddNodeSpeedTestParams) (NodeSpeedtest, error) {
	row := q.db.QueryRowContext(ctx, addNodeSpeedTest,
		arg.NodeID,
		arg.At,
		arg.PingMs,
		arg.JitterMs,
		arg.LossPct,
		arg.DownBps,
		arg.UpBps,
		arg.Error,
	)
	var i NodeSpeedtest
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.At,
		&i.PingMs,
		&i.JitterMs,
		&i.LossPct,
		&i.DownBps,
		&i.UpBps,
		&i.Error,
	)
	return i, err
}

const listNodeSpeedTests = `-- name: ListNodeSpeedTests :many
SELECT id, node_id, at, ping_ms, jitter_ms, loss_pct, down_bps, up_bps, error FROM node_speedtests WHERE node_id = $1 ORDER BY id DESC LIMIT $2
`

type ListNodeSpeedTestsParams struct {
	NodeID int64
	Limit  int32
}

func (q *Queries) ListNodeSpeedTests(ctx context.Context, arg ListNodeSpeedTestsParams) ([]NodeSpeedtest, error) {
	rows, err := q.db.QueryContext(ctx, listNodeSpeedTests, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSpeedtest{}
	for rows.Next() {
		var i NodeSpeedtest
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.At,
			&i.PingMs,
			&i.JitterMs,
			&i.LossPct,
			&i.DownBps,
			&i.UpBps,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneNodeSpeedTests = `-- name: PruneNodeSpeedTests :exec
DELETE FROM node_speedtests t WHERE t.node_id = $1::BIGINT AND t.id NOT IN (
  SELECT k.id FROM node_speedtests k WHERE k.node_id = $1::BIGINT ORDER BY k.id DESC LIMIT 100
)
`

// Keeps the latest hundred of a node.
func (q *Queries) PruneNodeSpeedTests(ctx context.Context, nodeID int64) error {
	_, err := q.db.ExecContext(ctx, pruneNodeSpeedTests, nodeID)
	return err
}
