// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: torrent.sql

package db

import (
	"context"
	"database/sql"
)

const activeTorrentBans = `-- name: ActiveTorrentBans :many
SELECT user_id, max(banned_until)::BIGINT AS banned_until FROM torrent_hits
WHERE banned_until > $1 AND lifted_at IS NULL
GROUP BY user_id
`

type ActiveTorrentBansRow struct {
	UserID      int64
	BannedUntil int64
}

func (q *Queries) ActiveTorrentBans(ctx context.Context, bannedUntil int64) ([]ActiveTorrentBansRow, error) {
	rows, err := q.db.QueryContext(ctx, activeTorrentBans, bannedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveTorrentBansRow{}
	for rows.Next() {
		var i ActiveTorrentBansRow
		if err := rows.Scan(&i.UserID, &i.BannedUntil); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addTorrentHit = `-- name: AddTorrentHit :one
INSERT INTO torrent_hits (user_id, node_id, ip, inbound, network, kind, dest, hits, at, banned_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type AddTorrentHitParams struct {
	UserID      int64
	NodeID      sql.NullInt64
	Ip          string
	Inbound     string
	Network     string
	Kind        string
	Dest        string
	Hits        int32
	At          int64
	BannedUntil int64
}

func (q *Queries) AddTorrentHit(ctx context.Context, arg AddTorrentHitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addTorrentHit,
		arg.UserID,
		arg.NodeID,
		arg.Ip,
		arg.Inbound,
		arg.Network,
		arg.Kind,
		arg.Dest,
		arg.Hits,
		arg.At,
		arg.BannedUntil,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastTorrentHitID = `-- name: LastTorrentHitID :one
SELECT COALESCE(max(id), 0)::BIGINT FROM torrent_hits
`

func (q *Queries) LastTorrentHitID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastTorrentHitID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const liftTorrentBans = `-- name: LiftTorrentBans :execrows
UPDATE torrent_hits SET lifted_at = $1::BIGINT
WHERE user_id = $2 AND banned_until > $1::BIGINT AND lifted_at IS NULL
`

type LiftTorrentBansParams struct {
	Now    int64
	UserID int64
}

func (q *Queries) LiftTorrentBans(ctx context.Context, arg LiftTorrentBansParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, liftTorrentBans, arg.Now, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTorrentHits = `-- name: ListTorrentHits :many
SELECT h.id, h.user_id, u.name AS user_name, h.node_id, COALESCE(n.name, '') AS node_name, h.ip, h.inbound,
  h.network, h.kind, h.dest, h.hits, h.at, h.banned_until, h.lifted_at
FROM torrent_hits h
JOIN users u ON u.id = h.user_id
LEFT JOIN nodes n ON n.id = h.node_id
WHERE ($2::BIGINT IS NULL OR h.user_id = $2)
  AND ($3::BIGINT IS NULL OR h.id < $3)
ORDER BY h.id DESC
LIMIT $1
`

type ListTorrentHitsParams struct {
	Limit  int32
	UserID sql.NullInt64
	Before sql.NullInt64
}

type ListTorrentHitsRow struct {
	ID          int64
	UserID      int64
	UserName    string
	NodeID      sql.NullInt64
	NodeName    string
	Ip          string
	Inbound     string
	Network     string
	Kind        string
	Dest        string
	Hits        int32
	At          int64
	BannedUntil int64
	LiftedAt    sql.NullInt64
}

func (q *Queries) ListTorrentHits(ctx context.Context, arg ListTorrentHitsParams) ([]ListTorrentHitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTorrentHits, arg.Limit, arg.UserID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTorrentHitsRow{}
	for rows.Next() {
		var i ListTorrentHitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.NodeID,
			&i.NodeName,
			&i.Ip,
			&i.Inbound,
			&i.Network,
			&i.Kind,
			&i.Dest,
			&i.Hits,
			&i.At,
			&i.BannedUntil,
			&i.LiftedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneTorrentHits = `-- name: PruneTorrentHits :exec
DELETE FROM torrent_hits WHERE at < $1 AND banned_until < $1
`

func (q *Queries) PruneTorrentHits(ctx context.Context, at int64) error {
	_, err := q.db.ExecContext(ctx, pruneTorrentHits, at)
	return err
}

const torrentHitsAfter = `-- name: TorrentHitsAfter :many
SELECT h.id, h.user_id, u.name AS user_name, COALESCE(n.name, '') AS node_name, h.ip, h.kind, h.dest, h.hits,
  h.at, h.banned_until
FROM torrent_hits h
JOIN users u ON u.id = h.user_id
LEFT JOIN nodes n ON n.id = h.node_id
WHERE h.id > $1
ORDER BY h.id
LIMIT $2
`

type TorrentHitsAfterParams struct {
	ID    int64
	Limit int32
}

type TorrentHitsAfterRow struct {
	ID          int64
	UserID      int64
	UserName    string
	NodeName    string
	Ip          string
	Kind        string
	Dest        string
	Hits        int32
	At          int64
	BannedUntil int64
}

func (q *Queries) TorrentHitsAfter(ctx context.Context, arg TorrentHitsAfterParams) ([]TorrentHitsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, torrentHitsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TorrentHitsAfterRow{}
	for rows.Next() {
		var i TorrentHitsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.NodeName,
			&i.Ip,
			&i.Kind,
			&i.Dest,
			&i.Hits,
			&i.At,
			&i.BannedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const torrentTrackerCatches = `-- name: TorrentTrackerCatches :one
SELECT COALESCE(sum(hits), 0)::BIGINT AS catches FROM torrent_hits h
WHERE h.user_id = $1 AND h.network = 'tcp' AND h.kind = 'tracker' AND h.at > $2
  AND h.at > COALESCE((SELECT max(l.lifted_at) FROM torrent_hits l WHERE l.user_id = $1), 0)
`

type TorrentTrackerCatchesParams struct {
	UserID int64
	At     int64
}

// How many HTTP tracker lines (TCP) a user was caught with since a time; a hit counts as
// many as it stands for. Lines before the admin last lifted the user's ban do not count.
func (q *Queries) TorrentTrackerCatches(ctx context.Context, arg TorrentTrackerCatchesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, torrentTrackerCatches, arg.UserID, arg.At)
	var catches int64
	err := row.Scan(&catches)
	return catches, err
}
