-- +goose Up
-- The torrent blocker's catches, as the nodes report them. A row with banned_until keeps
-- its user out of every node until then, unless the admin lifted it (lifted_at).
CREATE TABLE torrent_hits (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  node_id      BIGINT REFERENCES nodes(id) ON DELETE SET NULL,
  ip           TEXT NOT NULL,
  inbound      TEXT NOT NULL,
  network      TEXT NOT NULL,
  kind         TEXT NOT NULL,
  dest         TEXT NOT NULL,
  hits         INTEGER NOT NULL,
  at           BIGINT NOT NULL,
  banned_until BIGINT NOT NULL DEFAULT 0,
  lifted_at    BIGINT
);
CREATE INDEX torrent_hits_at ON torrent_hits (at DESC, id DESC);
CREATE INDEX torrent_hits_user ON torrent_hits (user_id, at DESC);
-- ActiveTorrentBans: the rows whose ban is still running, found without reading the whole log.
CREATE INDEX torrent_hits_active ON torrent_hits (banned_until) WHERE lifted_at IS NULL;

-- +goose Down
DROP TABLE torrent_hits;
