-- +goose Up
-- The speed tests of the nodes' own way to the internet, the latest hundred of each.
CREATE TABLE node_speedtests (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id   BIGINT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  at        BIGINT NOT NULL,
  ping_ms   DOUBLE PRECISION NOT NULL,
  jitter_ms DOUBLE PRECISION NOT NULL,
  loss_pct  DOUBLE PRECISION NOT NULL,
  down_bps  BIGINT NOT NULL,
  up_bps    BIGINT NOT NULL,
  error     TEXT NOT NULL DEFAULT ''
);
CREATE INDEX node_speedtests_node ON node_speedtests (node_id, id DESC);

-- +goose Down
DROP TABLE node_speedtests;
